server:
  servlet:
    context-path: /configuration-service
  port: ${SERVER_PORT:8888}
spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MatCoder77/flat-rental-config-repository.git
          default-label: main
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
    bus:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:http://localhost:9092}
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: ${HOST_NAME:localhost}
    metadata-map:
      configPath: ${server.servlet.context-path}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
logging:
  level:
    root: TRACE