server:
  servlet:
    context-path: /@project.artifactId@
  port: 0
api-docs:
  title: @project.name@ REST API
  version: @project.version@
  description: @project.description@
  termsOfServiceUrl: https://flatrental.com/terms
  license:
    name: Flat Rental License
    url: https://flatrental.com/license
  contact:
    name: Flat Rental Support
    email: support@flatretnal.com
    url: https://flatrental.com/support
spring:
  application:
    name: @project.artifactId@
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}